---
spring:
  application:
    name: "sapin"
  profiles:
    active: "dev"
  graphql:
    graphiql:
      enabled: true
---
spring:
  config:
    activate:
      on-profile: "dev"
  r2dbc:
    url: "r2dbc:postgresql://localhost:5432/db_sapin"
    username: "postgres"
    password: "postgres"
