---
spring:
  profiles:
    active: "dev"
---
spring:
  config:
    activate:
      on-profile: "dev"
  r2dbc:
    url: "r2dbc:postgresql://localhost:5432/db_sapin"
    username: "postgres"
    password: "postgres"
etl:
  scriptella:
    config:
      location: "etl"
  load:
    geopackage:
      location:
      - tableName: "ADM_0"
        level: 1
        isoIdColumnName: "GID_0"
        nameColumnName: "COUNTRY"
        srcIdColumnName: "GID_0"
      - tableName: "ADM_1"
        level: 2
        isoIdColumnName: "ISO_1"
        nameColumnName: "NAME_1"
        srcIdColumnName: "GID_1"
        levelNameColumnName: "TYPE_1"
        levelNameEnColumnName: "ENGTYPE_1"
        srcParentIdColumnName: "GID_0"
      natural-area:
      - tableName: "NaturaSite_polygon"
        nameColumnName: "SITENAME"
        srcIdColumnName: "SITECODE"
        typeCode: "NATURA2000"
        filter: "MS = 'FR'"
